name: Java CI with Maven

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_mvn:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        # Create settings.xml from the secret
    - name: Configure Maven settings.xml
      env:
        MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
      run: |
        echo "$MAVEN_SETTINGS" > $HOME/.m2/settings.xml

    # Create settings-security.xml from the secret
    - name: Configure Maven settings-security.xml
      env:
        MAVEN_SETTINGS_SECURITY: ${{ secrets.MAVEN_SETTINGS_SECURITY }}
      run: |
        echo "$MAVEN_SETTINGS_SECURITY" > $HOME/.m2/settings-security.xml
    # Run Maven tests
    - name: Run Tests
      run: mvn test --settings $HOME/.m2/settings.xml

    - name: Build with Maven
      run: mvn clean package --settings $HOME/.m2/settings.xml

  deploy_mvn:
    runs-on: ubuntu-latest
    needs: build_mvn
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Configure Maven settings.xml
        env:
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
        run: |
          echo "$MAVEN_SETTINGS" > $HOME/.m2/settings.xml

      # Create settings-security.xml from the secret
      - name: Configure Maven settings-security.xml
        env:
          MAVEN_SETTINGS_SECURITY: ${{ secrets.MAVEN_SETTINGS_SECURITY }}
        run: |
          echo "$MAVEN_SETTINGS_SECURITY" > $HOME/.m2/settings-security.xml

      - name: Deploy to GitHub Packages
        run: mvn deploy --settings $HOME/.m2/settings.xml

      #upload target maybe we will use it to build docker image....
      - name: Upload target as artifact
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/

